### ISSUE TITLE
Status code is always 0

### ISSUE THREAD

**Issue by jedisct1** [avidal/fastlike#10]
Looks like no matter what status code we try to return, the guest API always get `0`.

This can be easily reproduced by changing any of the `return XqdStatusOK` to something else in the functions called e.g. by the `testdata` example. 

I can observe the same behavior by calling these functions directly.

**Comment by jedisct1** [comment]
Looks like using the `XqdStatus` type causes `wasmtime-go` to consider that type an external reference, and not the `i32` type.

**Comment by jedisct1** [comment]
Yep, changing `XqdStatus` to use `int32` directly fixes this :/

**Comment by avidal** [comment]
It looks like the bug is in the wasmtime-go code that creates the func trampoline, which is responsible for converting arg and return types: https://github.com/bytecodealliance/wasmtime-go/blob/main/func.go#L316

When the func is being wrapped, it correctly creates the func signature to indicate that `XqdStatus` is an `int32`, but in the trampoline the type is unknown, which falls back to the `default` branch, which results in a trap from wasmtime because the return type doesn't match. Curiously, I believe this means that every function call is technically "broken" but is somehow masked.

**Comment by avidal** [comment]
I patched wasmtime-go to cast this type into an int32 in the trampoline which avoids the trap, but it's still confusing semantics. It sets the result type to, eg, `int32` instead of the aliased type.

I think it's probably best to avoid type aliases in function signatures. I'll raise the issue in the upstream and see if Alex has any comments.
